Added Linear Search
GDSC-AUM/OpenOcto-DSA pull request #65
Opened 2021-10-14 18:51 UTC by ayushanand09

#### What was changed?

#### Checklist

- [x] Added description of change.
- [x] I acknowledge that all my contributions will be made under the project's license.

**Program Request** 
- [x] Added file name matches **File name guidelines** mentioned in [Contributing guidelines](https://github.com/GDSC-AUM/OpenOcto-DSA/blob/main/CONTRIBUTING.md)
- [x] Updated documentation OR created an issue for someone else to update the documentation.

**Bug Fix** 
- [x] Bug is now fixed and program now behaves as expected.

**Documentation Update** 
- [x] Documenation matches **format** mentioned in [Contributing guidelines](https://github.com/GDSC-AUM/OpenOcto-DSA/blob/main/CONTRIBUTING.md)
- [x] If applicable, referenced sources have been linked.

**Program Improvement**
- [x] The improvements made are not just visual and actually makes the program more efficient. 

Notes: This is with respect to issue number #11

2021-10-15 08:47 UTC, unshDee requested changes
@ayushanand09 you've added linear_search twice, one inside the `searching` folder and one in the root. 
Please remove the one in root and I'll approve

2021-10-15 09:16 UTC, ayushanand09 commented
Hey @unshDee ,
I have deleted **_"linear_search.cpp"_** file in the root.
Please do check it out.

Thanks,
Ayush

2021-10-16 23:56 UTC, bhantsi approved these changes

2021-10-18 18:02 UTC, unshDee approved these changes
@ayushanand09 
Thanks! Approved

2021-10-18 18:03 UTC, merged